/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package broadinstitute.org;

import htsjdk.io.HtsPath;
import htsjdk.variant.vcf.VCFFileReader;
import org.broadinstitute.pgen.PgenWriter;
import org.testng.annotations.*;

import java.io.File;

public class PgenRunnerTest {
    @Test
    public void testPgenWriter() {

        try (final VCFFileReader reader = new VCFFileReader(new File("src/test/resources/CEUtrioTest.vcf"), false)) {
            try (final PgenWriter pgenWriter = new PgenWriter(
                    new HtsPath("temp.pgen"),
                    reader.getFileHeader(),
                    PgenWriter.PgenWriteMode.PGEN_FILE_MODE_WRITE_SEPARATE_INDEX,
                    PgenWriter.VARIANT_COUNT_UNKNOWN,
                    PgenWriter.PLINK2_MAX_ALTERNATE_ALLELES)) {

                reader.forEach(vc -> pgenWriter.add(vc));
            }
        }
    }

    @Test
    public void testNativeUtils() {
        // otherwise, load it from a jar file on the classpath
        NativeLibraryUtils.loadLibraryFromClasspath(
                NativeLibraryUtils.runningOnMac() ?
                        "/libpgen.dylib" :
                        "/libpgen.so"
        );
    }
}
