/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package broadinstitute.org;

import htsjdk.io.HtsPath;
import htsjdk.variant.vcf.VCFFileReader;
import org.broadinstitute.pgen.PgenWriter;

import java.io.File;
import java.util.EnumSet;

public class PgenRunner {
    public static void main(String[] args) {
        if (args.length == 0) {
            try (final VCFFileReader reader = new VCFFileReader(new File("app/src/test/resources/CEUtrioTest.vcf"), false)) {
                try (final PgenWriter pgenWriter = new PgenWriter(
                        new HtsPath("temp.pgen"),
                        reader.getFileHeader(),
                        PgenWriter.PgenWriteMode.PGEN_FILE_MODE_WRITE_SEPARATE_INDEX,
                        EnumSet.noneOf(PgenWriter.PgenWriteFlag.class),
                        PgenWriter.PgenChromosomeCode.PLINK_CHROMOSOME_CODE_MT,
                        false,
                        PgenWriter.VARIANT_COUNT_UNKNOWN,
                        PgenWriter.PLINK2_MAX_ALTERNATE_ALLELES,
                        null)) {
                    reader.forEach(vc -> pgenWriter.add(vc));
                }
            }
        } else {
            System.out.println("Args not implemented");
        }
    }
}
